const stocks = [
  {code:'2330',name:'台積電',price:1040,change:1.46,rsi:58.2,volume:1.3,strength:4,type:'volume',signal:'量能突破',color:'#2c62c4',history:[998,1005,1002,1016,1010,1024,1020,1032,1028,1040]},
  {code:'2317',name:'鴻海',price:198.5,change:-0.75,rsi:29.8,volume:1.8,strength:5,type:'rebound',signal:'強力反彈',color:'#7556b8',history:[211,207,203,200,195,191,193,192,196,198.5]},
  {code:'2454',name:'聯發科',price:1295,change:2.37,rsi:73.4,volume:2.1,strength:4,type:'hot',signal:'短線過熱',color:'#d2664f',history:[1190,1205,1222,1214,1240,1255,1270,1264,1282,1295]},
  {code:'2382',name:'廣達',price:287.5,change:1.95,rsi:35.1,volume:2.6,strength:4,type:'rebound',signal:'反彈確認',color:'#2a997c',history:[302,297,292,285,279,276,279,282,284,287.5]},
  {code:'3231',name:'緯創',price:111.5,change:4.69,rsi:68.7,volume:3.2,strength:5,type:'volume',signal:'量價齊揚',color:'#3a83ad',history:[99,100,102,101,103,105,104,107,109,111.5]},
  {code:'2603',name:'長榮',price:226,change:-2.16,rsi:76.2,volume:1.5,strength:3,type:'hot',signal:'漲多拉回',color:'#39956e',history:[203,207,211,219,225,232,235,231,228,226]},
  {code:'2881',name:'富邦金',price:92.4,change:0.65,rsi:43.8,volume:1.1,strength:3,type:'rebound',signal:'底部觀察',color:'#4567aa',history:[94,93,91,89,88,89.5,90,91,91.8,92.4]},
  {code:'3661',name:'世芯-KY',price:2510,change:3.29,rsi:79.1,volume:2.8,strength:5,type:'hot',signal:'高檔過熱',color:'#9c5c79',history:[2230,2290,2310,2370,2420,2390,2450,2480,2470,2510]}
];
const state={filter:'all',query:'',watchOnly:false,watchlist:new Set(['2330','2317'])};
const rows=document.querySelector('#stockRows');
const typeLabels={rebound:'反彈機會',hot:'過熱警示',volume:'量價異常'};
function render(){
  const filtered=stocks.filter(s=>(state.filter==='all'||s.type===state.filter)&&(!state.query||`${s.code}${s.name}`.toLowerCase().includes(state.query))&&(!state.watchOnly||state.watchlist.has(s.code)));
  rows.innerHTML=filtered.map(s=>`<tr data-code="${s.code}"><td><div class="stock-cell"><span class="stock-logo" style="background:${s.color}">${s.name.slice(0,1)}</span><span><strong>${s.name}</strong><small>${s.code}</small></span></div></td><td class="price">$${s.price.toLocaleString()}</td><td class="change ${s.change>=0?'up':'down'}">${s.change>=0?'+':''}${s.change.toFixed(2)}%</td><td class="rsi ${s.rsi>70?'down':s.rsi<35?'up':''}">${s.rsi}<small>${s.rsi>70?'過熱':s.rsi<35?'超跌':'中性'}</small></td><td><span class="volume-ratio">${s.volume.toFixed(1)}x</span></td><td><div class="strength"><span class="strength-bar">${[1,2,3,4,5].map(n=>`<i class="${n<=s.strength?'on '+(s.type==='rebound'?'green':s.type==='hot'?'red':'orange'):''}"></i>`).join('')}</span><span>${s.strength>=5?'強':s.strength>=4?'偏強':'中等'}</span></div></td><td><span class="signal-pill ${s.type}">●&nbsp; ${s.signal}</span></td><td><button class="row-action ${state.watchlist.has(s.code)?'starred':''}" data-star="${s.code}" aria-label="切換 ${s.name} 自選">${state.watchlist.has(s.code)?'★':'☆'}</button></td></tr>`).join('');
  document.querySelector('#emptyState').hidden=filtered.length!==0;
  document.querySelector('#resultCount').textContent=`顯示 ${filtered.length} 筆，共 ${state.filter==='all'?48:filtered.length} 筆`;
}
document.querySelectorAll('.tabs button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.tabs .active').classList.remove('active');button.classList.add('active');state.filter=button.dataset.filter;render()}));
['tableSearch','globalSearch'].forEach(id=>document.querySelector(`#${id}`).addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();render()}));
document.querySelector('#watchOnly').addEventListener('click',e=>{state.watchOnly=!state.watchOnly;e.currentTarget.classList.toggle('active',state.watchOnly);render()});
rows.addEventListener('click',e=>{const star=e.target.closest('[data-star]');if(star){const code=star.dataset.star;state.watchlist.has(code)?state.watchlist.delete(code):state.watchlist.add(code);render();showToast(state.watchlist.has(code)?'已加入觀察清單':'已從觀察清單移除');return}const row=e.target.closest('tr');if(row)openStock(stocks.find(s=>s.code===row.dataset.code))});
const dialog=document.querySelector('#stockDialog');
function openStock(s){document.querySelector('#dialogCode').textContent=s.code;document.querySelector('#dialogName').textContent=s.name;document.querySelector('#dialogPrice').textContent=`$${s.price.toLocaleString()}`;const ch=document.querySelector('#dialogChange');ch.textContent=`${s.change>=0?'+':''}${s.change.toFixed(2)}% 今日`;ch.className=s.change>=0?'up':'down';const pill=document.querySelector('#dialogSignal');pill.textContent=s.signal;pill.className=`signal-pill ${s.type}`;document.querySelector('#dialogMetrics').innerHTML=`<div><small>RSI (14)</small><strong>${s.rsi}</strong></div><div><small>成交量比</small><strong>${s.volume}x</strong></div><div><small>訊號強度</small><strong>${s.strength} / 5</strong></div>`;document.querySelector('#dialogInsight').textContent=s.type==='rebound'?`${s.name} 的 RSI 已進入低檔區並出現價格止穩，若成交量持續放大，可留意短線反彈延續性。建議設定停損並分批布局。`:s.type==='hot'?`${s.name} 近期漲幅與 RSI 均處高檔，短線追價風險升高。可觀察量縮或跌破短期均線，已持有者宜留意獲利保護。`:`${s.name} 今日成交量顯著高於近期平均，價格動能同步增強。仍需確認後續量能延續，避免單日爆量後快速回落。`;dialog.showModal();requestAnimationFrame(()=>drawChart(s))}
function drawChart(s){const canvas=document.querySelector('#priceChart'),ctx=canvas.getContext('2d'),dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);const pad=24,min=Math.min(...s.history),max=Math.max(...s.history),pts=s.history.map((v,i)=>[pad+i*(w-pad*2)/(s.history.length-1),h-pad-(v-min)/(max-min||1)*(h-pad*2)]);ctx.strokeStyle='#e7ebf1';ctx.lineWidth=1;[.25,.5,.75].forEach(p=>{ctx.beginPath();ctx.moveTo(pad,h*p);ctx.lineTo(w-pad,h*p);ctx.stroke()});const grad=ctx.createLinearGradient(0,20,0,h);grad.addColorStop(0,s.type==='hot'?'#e54b6240':'#2864dc45');grad.addColorStop(1,'#ffffff05');ctx.beginPath();ctx.moveTo(pts[0][0],h-pad);pts.forEach(p=>ctx.lineTo(...p));ctx.lineTo(pts.at(-1)[0],h-pad);ctx.fillStyle=grad;ctx.fill();ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=s.type==='hot'?'#e54b62':'#2864dc';ctx.lineWidth=2.5;ctx.stroke()}
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.querySelector('#refreshButton').addEventListener('click',e=>{e.currentTarget.classList.add('loading');setTimeout(()=>{e.currentTarget.classList.remove('loading');showToast('分析資料已更新')},700)});
document.querySelector('#loadMore').addEventListener('click',()=>showToast('已載入最新 48 筆訊號'));
document.querySelector('#filterButton').addEventListener('click',()=>showToast('可使用上方頁籤快速篩選訊號'));
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();document.querySelector('#globalSearch').focus()}if(e.key==='Escape'&&dialog.open)dialog.close()});
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
render();
